### ISSUE TITLE
Dockerize Mail Service

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Mail-Service#1]
Make the Lif Mail service work with Docker to make deployment and hosting easier.

**Tasks**

- [x] Create a Dockerfile for making new images
- [x] Create a public Docker Hub repo for Mail Service
- [ ] Create a GitHub automation to automatically build and push new images on release
