### ISSUE TITLE
Add support for account recovery emails

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Mail-Service#5]
Add a route that allows Lif Auth Server to send account recovery emails to users. 

### Tasks
- [ ] Create account recovery email template
- [ ] Add a route for Lif Auth Server to send emails
- [ ] Add email functionality to route
