### ISSUE TITLE
Add Service Email Support

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Mail-Service#6]
Add a system to servers for Lif Platforms services can send emails to users.

### Tasks
- [x] Make a route for services to send emails
- [x] Add access token support
- [x] Make Mail Service send emails with Nylas API.
